### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by deepch** [atagirov/onvif4go#4]
Can I use this code and modify it.

**Comment by jpwhitemn** [comment]
Arthur - we'd like to consider using this library as part of the EdgeX Foundry open source project but we absolutely need a license file and know this is contributed into open source before we do so.  Can you add an open source license file to your work here?

**Comment by jdharms** [comment]
Adding on to @jpwhitemn, we would also love to contribute to the library and implement more of the ONVIF standard.

**Comment by atagirov** [comment]
We are moved repository and added MIT license.
